// Actor templates + loot tables. Exemplars: melee creature, pack creature,
// melee humanoid, ranged humanoid, boss, scheduled villager, merchant.
// All names, dialogue, and lore are original Claurim material.

import type { ActorTemplate, LootTableDef } from './schema';

export const LOOT_TABLES: Record<string, LootTableDef> = {
  wolf_loot: {
    id: 'wolf_loot',
    entries: [{ itemId: 'wolf_pelt', min: 1, max: 2, chance: 0.9 }],
    goldMin: 0,
    goldMax: 0,
  },
  bandit_loot: {
    id: 'bandit_loot',
    entries: [
      { itemId: 'worn_dagger', min: 1, max: 1, chance: 0.35 },
      { itemId: 'healing_draught', min: 1, max: 1, chance: 0.25 },
      { itemId: 'arrow', min: 3, max: 10, chance: 0.5 },
    ],
    goldMin: 2,
    goldMax: 14,
  },
  wight_loot: {
    id: 'wight_loot',
    entries: [
      { itemId: 'steel_sword', min: 1, max: 1, chance: 1 },
      { itemId: 'duskhollow_ore', min: 1, max: 1, chance: 1 },
    ],
    goldMin: 20,
    goldMax: 45,
  },
  mine_cache: {
    id: 'mine_cache',
    entries: [
      { itemId: 'healing_draught', min: 1, max: 2, chance: 1 },
      { itemId: 'ember_cap', min: 1, max: 3, chance: 0.8 },
    ],
    goldMin: 5,
    goldMax: 20,
  },
  journal_cache: {
    id: 'journal_cache',
    entries: [{ itemId: 'prospectors_journal', min: 1, max: 1, chance: 1 }],
    goldMin: 0,
    goldMax: 0,
  },
  merchant_stock: {
    id: 'merchant_stock',
    entries: [
      { itemId: 'iron_sword', min: 1, max: 1, chance: 1 },
      { itemId: 'hunting_bow', min: 1, max: 1, chance: 1 },
      { itemId: 'arrow', min: 30, max: 30, chance: 1 },
      { itemId: 'leather_cuirass', min: 1, max: 1, chance: 1 },
      { itemId: 'leather_boots', min: 1, max: 1, chance: 1 },
      { itemId: 'wooden_shield', min: 1, max: 1, chance: 1 },
      { itemId: 'healing_draught', min: 4, max: 4, chance: 1 },
      { itemId: 'stamina_tonic', min: 3, max: 3, chance: 1 },
      { itemId: 'bread', min: 6, max: 6, chance: 1 },
    ],
    goldMin: 0,
    goldMax: 0,
  },
};

export const ACTORS: Record<string, ActorTemplate> = {
  // --- creatures -----------------------------------------------------------
  frostfang_wolf: {
    id: 'frostfang_wolf',
    name: 'Frostfang Wolf',
    kind: 'creature',
    level: 2,
    baseStats: { maxHealth: 30, moveSpeed: 6.2 },
    attack: 'melee',
    attackDamage: 6,
    attackChannel: 'physical',
    aggressive: true,
    fleeBelowHealthFrac: 0.15,
    perceptionRange: 26,
    lootTable: 'wolf_loot',
    archetype: 'wolf',
    respawnGameHours: 48,
  },
  marsh_rat: {
    id: 'marsh_rat',
    name: 'Marsh Rat',
    kind: 'creature',
    level: 1,
    baseStats: { maxHealth: 14, moveSpeed: 5.0 },
    attack: 'melee',
    attackDamage: 3,
    attackChannel: 'physical',
    aggressive: true,
    fleeBelowHealthFrac: 0.3,
    perceptionRange: 14,
    archetype: 'rat',
    respawnGameHours: 24,
  },

  // --- hostile humanoids ---------------------------------------------------
  redclaw_raider: {
    id: 'redclaw_raider',
    name: 'Redclaw Raider',
    kind: 'creature',
    level: 3,
    baseStats: { maxHealth: 45, armor: 8 },
    attack: 'melee',
    attackDamage: 8,
    attackChannel: 'physical',
    aggressive: true,
    fleeBelowHealthFrac: 0.1,
    perceptionRange: 30,
    lootTable: 'bandit_loot',
    factionId: 'redclaw',
    archetype: 'bandit',
    respawnGameHours: 'never',
  },
  redclaw_archer: {
    id: 'redclaw_archer',
    name: 'Redclaw Archer',
    kind: 'creature',
    level: 3,
    baseStats: { maxHealth: 34, armor: 4 },
    attack: 'ranged',
    attackDamage: 7,
    attackChannel: 'physical',
    aggressive: true,
    fleeBelowHealthFrac: 0.2,
    perceptionRange: 38,
    lootTable: 'bandit_loot',
    factionId: 'redclaw',
    archetype: 'bandit_archer',
    respawnGameHours: 'never',
  },

  // --- boss ----------------------------------------------------------------
  barrow_wight: {
    id: 'barrow_wight',
    name: 'The Pale Warden',
    kind: 'creature',
    level: 6,
    baseStats: { maxHealth: 140, armor: 14, moveSpeed: 4.2, resistFrost: 0.5 },
    attack: 'melee',
    attackDamage: 14,
    attackChannel: 'frost',
    aggressive: true,
    fleeBelowHealthFrac: 0,
    perceptionRange: 24,
    lootTable: 'wight_loot',
    archetype: 'wight',
    respawnGameHours: 'never',
  },

  // --- villagers -----------------------------------------------------------
  maera: {
    id: 'maera',
    name: 'Maera Fenn',
    kind: 'npc',
    level: 4,
    baseStats: { maxHealth: 60 },
    attack: 'melee',
    attackDamage: 5,
    attackChannel: 'physical',
    aggressive: false,
    fleeBelowHealthFrac: 0.5,
    perceptionRange: 20,
    factionId: 'fenharrow',
    dialogueId: 'maera_dialogue',
    merchant: { buys: ['weapon', 'armor', 'misc', 'ingredient', 'consumable'], stockTable: 'merchant_stock', gold: 300 },
    schedule: [
      { fromHour: 7, toHour: 21, spaceId: 'fenharrow_inn', x: 4, z: 3, activity: 'work' },
      { fromHour: 21, toHour: 24, spaceId: 'fenharrow_inn', x: -5, z: 7, activity: 'sleep' },
      { fromHour: 0, toHour: 7, spaceId: 'fenharrow_inn', x: -5, z: 7, activity: 'sleep' },
    ],
    archetype: 'villager_f',
    respawnGameHours: 'never',
  },
  bronn: {
    id: 'bronn',
    name: 'Bronn Hale',
    kind: 'npc',
    level: 5,
    baseStats: { maxHealth: 80 },
    attack: 'melee',
    attackDamage: 9,
    attackChannel: 'physical',
    aggressive: false,
    fleeBelowHealthFrac: 0.25,
    perceptionRange: 20,
    factionId: 'fenharrow',
    dialogueId: 'bronn_dialogue',
    schedule: [
      { fromHour: 6, toHour: 20, spaceId: 'kaldwyn', x: 62, z: 136, activity: 'work' },
      { fromHour: 20, toHour: 24, spaceId: 'fenharrow_inn', x: 3, z: 8, activity: 'idle' },
      { fromHour: 0, toHour: 6, spaceId: 'kaldwyn', x: 66, z: 132, activity: 'sleep' },
    ],
    archetype: 'villager_m',
    respawnGameHours: 'never',
  },
  ysolde: {
    id: 'ysolde',
    name: 'Ysolde Varr',
    kind: 'npc',
    level: 3,
    baseStats: { maxHealth: 55 },
    attack: 'ranged',
    attackDamage: 7,
    attackChannel: 'physical',
    aggressive: false,
    fleeBelowHealthFrac: 0.3,
    perceptionRange: 30,
    factionId: 'fenharrow',
    dialogueId: 'ysolde_dialogue',
    schedule: [
      { fromHour: 5, toHour: 18, spaceId: 'kaldwyn', x: 10, z: 185, activity: 'wander' },
      { fromHour: 18, toHour: 23, spaceId: 'fenharrow_inn', x: 6, z: 8, activity: 'idle' },
      { fromHour: 23, toHour: 24, spaceId: 'kaldwyn', x: 24, z: 168, activity: 'sleep' },
      { fromHour: 0, toHour: 5, spaceId: 'kaldwyn', x: 24, z: 168, activity: 'sleep' },
    ],
    archetype: 'villager_f',
    respawnGameHours: 'never',
  },
};
