// Actor templates + loot tables, tuned for MMO party play (D-018 targets:
// overworld solo-viable, dungeons for ~3-5, boss defeats an unprepared solo).
// Encounter roles: melee / ranged / support; tiers: standard / veteran /
// elite / boss. Abilities + phases are data interpreted by ai/abilities.ts.
//
// NAMING (see docs/project/NAMING_GUIDE.md): internal ids are STABLE and never
// renamed; display names are original. Audit 2026-07-31: "Ysolde" was one
// letter from a well-known inspiration NPC and became "Eydris Varr";
// "Bronn" collided with a famous fantasy sellsword and became "Brandvar Hale".

import type { ActorTemplate, LootTableDef } from './schema';

export const LOOT_TABLES: Record<string, LootTableDef> = {
  wolf_loot: {
    id: 'wolf_loot',
    entries: [{ itemId: 'wolf_pelt', min: 1, max: 2, chance: 0.9 }],
    goldMin: 0,
    goldMax: 0,
  },
  boar_loot: {
    id: 'boar_loot',
    entries: [{ itemId: 'briar_tusk', min: 1, max: 2, chance: 0.85 }],
    goldMin: 0,
    goldMax: 0,
  },
  matriarch_loot: {
    id: 'matriarch_loot',
    entries: [
      { itemId: 'briar_tusk', min: 2, max: 3, chance: 1 },
      { itemId: 'fur_mantle', min: 1, max: 1, chance: 0.2 },
    ],
    goldMin: 4,
    goldMax: 12,
  },
  alpha_loot: {
    id: 'alpha_loot',
    entries: [
      { itemId: 'wolf_pelt', min: 2, max: 3, chance: 1 },
      { itemId: 'fur_mantle', min: 1, max: 1, chance: 0.25 },
    ],
    goldMin: 0,
    goldMax: 0,
  },
  bandit_loot: {
    id: 'bandit_loot',
    entries: [
      { itemId: 'worn_dagger', min: 1, max: 1, chance: 0.35 },
      { itemId: 'healing_draught', min: 1, max: 1, chance: 0.35 },
      { itemId: 'arrow', min: 3, max: 10, chance: 0.5 },
    ],
    goldMin: 3,
    goldMax: 18,
  },
  reaver_loot: {
    id: 'reaver_loot',
    entries: [
      { itemId: 'iron_sword', min: 1, max: 1, chance: 0.5 },
      { itemId: 'healing_draught', min: 1, max: 2, chance: 0.6 },
    ],
    goldMin: 10,
    goldMax: 30,
  },
  sentinel_loot: {
    id: 'sentinel_loot',
    entries: [
      { itemId: 'iron_mace', min: 1, max: 1, chance: 0.45 },
      { itemId: 'healing_draught', min: 1, max: 1, chance: 0.5 },
    ],
    goldMin: 8,
    goldMax: 24,
  },
  wight_loot: {
    id: 'wight_loot',
    entries: [
      { itemId: 'steel_sword', min: 1, max: 1, chance: 1 },
      { itemId: 'duskhollow_ore', min: 1, max: 1, chance: 1 },
      { itemId: 'healing_draught', min: 1, max: 2, chance: 0.8 },
    ],
    goldMin: 25,
    goldMax: 60,
  },
  mine_cache: {
    id: 'mine_cache',
    entries: [
      { itemId: 'healing_draught', min: 1, max: 2, chance: 1 },
      { itemId: 'ember_cap', min: 1, max: 3, chance: 0.8 },
    ],
    goldMin: 5,
    goldMax: 20,
  },
  burrow_cache: {
    id: 'burrow_cache',
    entries: [
      { itemId: 'hide_cuirass', min: 1, max: 1, chance: 0.5 },
      { itemId: 'fur_boots', min: 1, max: 1, chance: 0.4 },
      { itemId: 'stamina_tonic', min: 1, max: 2, chance: 1 },
      { itemId: 'frost_moss', min: 1, max: 3, chance: 0.8 },
    ],
    goldMin: 4,
    goldMax: 16,
  },
  journal_cache: {
    id: 'journal_cache',
    entries: [{ itemId: 'prospectors_journal', min: 1, max: 1, chance: 1 }],
    goldMin: 0,
    goldMax: 0,
  },
  gloamroot_cache: {
    id: 'gloamroot_cache',
    entries: [
      { itemId: 'healing_draught', min: 1, max: 2, chance: 1 },
      { itemId: 'briar_tusk', min: 1, max: 2, chance: 0.8 },
      { itemId: 'ember_cap', min: 1, max: 3, chance: 0.7 },
    ],
    goldMin: 6,
    goldMax: 20,
  },
  stone_offering: {
    id: 'stone_offering',
    entries: [
      { itemId: 'frost_moss', min: 1, max: 2, chance: 1 },
      { itemId: 'primer_stoneward', min: 1, max: 1, chance: 0.25 },
    ],
    goldMin: 3,
    goldMax: 11,
  },
  merchant_stock: {
    id: 'merchant_stock',
    entries: [
      { itemId: 'iron_sword', min: 2, max: 2, chance: 1 },
      { itemId: 'iron_axe', min: 2, max: 2, chance: 1 },
      { itemId: 'iron_dagger', min: 2, max: 2, chance: 1 },
      { itemId: 'iron_mace', min: 2, max: 2, chance: 1 },
      { itemId: 'ironbound_bow', min: 2, max: 2, chance: 1 },
      { itemId: 'hunting_bow', min: 2, max: 2, chance: 1 },
      { itemId: 'arrow', min: 60, max: 60, chance: 1 },
      { itemId: 'leather_cuirass', min: 2, max: 2, chance: 1 },
      { itemId: 'leather_boots', min: 2, max: 2, chance: 1 },
      { itemId: 'wooden_shield', min: 2, max: 2, chance: 1 },
      { itemId: 'hide_cuirass', min: 2, max: 2, chance: 1 },
      { itemId: 'hide_cap', min: 2, max: 2, chance: 1 },
      { itemId: 'hide_boots', min: 2, max: 2, chance: 1 },
      { itemId: 'hide_shield', min: 2, max: 2, chance: 1 },
      { itemId: 'fur_cuirass', min: 2, max: 2, chance: 1 },
      { itemId: 'fur_hood', min: 2, max: 2, chance: 1 },
      { itemId: 'fur_boots', min: 2, max: 2, chance: 1 },
      { itemId: 'fur_mantle', min: 2, max: 2, chance: 1 },
      { itemId: 'healing_draught', min: 8, max: 8, chance: 1 },
      { itemId: 'stamina_tonic', min: 5, max: 5, chance: 1 },
      { itemId: 'bread', min: 10, max: 10, chance: 1 },
      { itemId: 'primer_flamebolt', min: 1, max: 1, chance: 1 },
      { itemId: 'primer_frostspike', min: 1, max: 1, chance: 1 },
      { itemId: 'primer_stormneedle', min: 1, max: 1, chance: 1 },
      { itemId: 'primer_mend_wounds', min: 1, max: 1, chance: 1 },
      { itemId: 'primer_stoneward', min: 1, max: 1, chance: 1 },
      { itemId: 'primer_veilstep', min: 1, max: 1, chance: 1 },
    ],
    goldMin: 0,
    goldMax: 0,
  },
};

export const ACTORS: Record<string, ActorTemplate> = {
  // --- overworld creatures (solo-viable) -----------------------------------
  ridge_hart: {
    id: 'ridge_hart',
    name: 'Kaldwyn Ridge Hart',
    kind: 'creature',
    level: 1,
    baseStats: { maxHealth: 36, moveSpeed: 5.6 },
    attack: 'melee',
    attackDamage: 4,
    attackChannel: 'physical',
    aggressive: false,
    fleeBelowHealthFrac: 0.9,
    perceptionRange: 20,
    factionId: 'ridge_herd',
    archetype: 'hart',
    ambientWanderRadius: 10,
    respawnGameHours: 24,
  },
  briarboar: {
    id: 'briarboar',
    name: 'Briarboar',
    kind: 'creature',
    level: 3,
    tier: 'standard',
    role: 'melee',
    baseStats: { maxHealth: 62, armor: 8, moveSpeed: 5.1 },
    attack: 'melee',
    attackDamage: 10,
    attackChannel: 'physical',
    aggressive: true,
    fleeBelowHealthFrac: 0.15,
    perceptionRange: 22,
    lootTable: 'boar_loot',
    factionId: 'gloamroot_sounder',
    archetype: 'boar',
    respawnGameHours: 48,
  },
  briarboar_matriarch: {
    id: 'briarboar_matriarch',
    name: 'Root-Tusk Matriarch',
    kind: 'creature',
    level: 5,
    tier: 'veteran',
    role: 'melee',
    baseStats: { maxHealth: 135, armor: 14, moveSpeed: 5.3 },
    attack: 'melee',
    attackDamage: 15,
    attackChannel: 'physical',
    aggressive: true,
    fleeBelowHealthFrac: 0,
    perceptionRange: 24,
    lootTable: 'matriarch_loot',
    factionId: 'gloamroot_sounder',
    archetype: 'boar',
    respawnGameHours: 48,
    abilities: [{
      id: 'root_tusk_charge',
      kind: 'frontal_cone',
      telegraphTicks: 34,
      interruptible: true,
      cooldownTicks: 210,
      damage: 24,
      channel: 'physical',
      coneDegrees: 70,
      range: 4.8,
    }],
  },
  frostfang_wolf: {
    id: 'frostfang_wolf',
    name: 'Frostfang Wolf',
    kind: 'creature',
    level: 2,
    tier: 'standard',
    role: 'melee',
    baseStats: { maxHealth: 40, moveSpeed: 6.2 },
    attack: 'melee',
    attackDamage: 8,
    attackChannel: 'physical',
    aggressive: true,
    fleeBelowHealthFrac: 0.15,
    perceptionRange: 26,
    lootTable: 'wolf_loot',
    factionId: 'frostfang_pack',
    archetype: 'wolf',
    respawnGameHours: 48,
  },
  frostfang_alpha: {
    id: 'frostfang_alpha',
    name: 'Rimehowl Alpha',
    kind: 'creature',
    level: 4,
    tier: 'veteran',
    role: 'melee',
    baseStats: { maxHealth: 95, armor: 6, moveSpeed: 6.4 },
    attack: 'melee',
    attackDamage: 11,
    attackChannel: 'physical',
    aggressive: true,
    fleeBelowHealthFrac: 0,
    perceptionRange: 28,
    lootTable: 'alpha_loot',
    factionId: 'frostfang_pack',
    archetype: 'wolf',
    respawnGameHours: 48,
    abilities: [
      {
        id: 'rimehowl_sweep',
        kind: 'frontal_cone',
        telegraphTicks: 36,
        interruptible: true,
        cooldownTicks: 210,
        damage: 18,
        channel: 'physical',
        coneDegrees: 95,
        range: 3.6,
      },
    ],
  },

  // --- Duskhollow trash: rats + a support matron (target-priority lesson) --
  marsh_rat: {
    id: 'marsh_rat',
    name: 'Marsh Rat',
    kind: 'creature',
    level: 2,
    tier: 'standard',
    role: 'melee',
    baseStats: { maxHealth: 22, moveSpeed: 5.2 },
    attack: 'melee',
    attackDamage: 5,
    attackChannel: 'physical',
    aggressive: true,
    fleeBelowHealthFrac: 0.2,
    perceptionRange: 16,
    factionId: 'duskhollow_brood',
    archetype: 'rat',
    respawnGameHours: 'never',
  },
  mire_matron: {
    id: 'mire_matron',
    name: 'Mire Matron',
    kind: 'creature',
    level: 4,
    tier: 'veteran',
    role: 'support',
    baseStats: { maxHealth: 70, moveSpeed: 4.4 },
    attack: 'melee',
    attackDamage: 4,
    attackChannel: 'poison',
    aggressive: true,
    fleeBelowHealthFrac: 0,
    perceptionRange: 22,
    factionId: 'duskhollow_brood',
    archetype: 'rat_matron',
    respawnGameHours: 'never',
    abilities: [
      {
        id: 'brood_mending',
        kind: 'heal_ally',
        telegraphTicks: 36,
        interruptible: true,
        cooldownTicks: 180,
        healAmount: 18,
        range: 20,
      },
    ],
  },

  // --- Redclaw gate camp: mixed pull with a veteran ------------------------
  redclaw_raider: {
    id: 'redclaw_raider',
    name: 'Redclaw Raider',
    kind: 'creature',
    level: 3,
    tier: 'standard',
    role: 'melee',
    baseStats: { maxHealth: 70, armor: 10 },
    attack: 'melee',
    attackDamage: 12,
    attackChannel: 'physical',
    aggressive: true,
    fleeBelowHealthFrac: 0.1,
    perceptionRange: 30,
    lootTable: 'bandit_loot',
    factionId: 'redclaw',
    archetype: 'bandit',
    respawnGameHours: 'never',
  },
  redclaw_archer: {
    id: 'redclaw_archer',
    name: 'Redclaw Archer',
    kind: 'creature',
    level: 3,
    tier: 'standard',
    role: 'ranged',
    baseStats: { maxHealth: 50, armor: 4 },
    attack: 'ranged',
    attackDamage: 11,
    attackChannel: 'physical',
    aggressive: true,
    fleeBelowHealthFrac: 0.2,
    perceptionRange: 38,
    lootTable: 'bandit_loot',
    factionId: 'redclaw',
    archetype: 'bandit_archer',
    respawnGameHours: 'never',
  },
  redclaw_reaver: {
    id: 'redclaw_reaver',
    name: 'Redclaw Reaver',
    kind: 'creature',
    level: 5,
    tier: 'veteran',
    role: 'melee',
    baseStats: { maxHealth: 140, armor: 16, moveSpeed: 4.6 },
    attack: 'melee',
    attackDamage: 16,
    attackChannel: 'physical',
    aggressive: true,
    fleeBelowHealthFrac: 0,
    perceptionRange: 30,
    lootTable: 'reaver_loot',
    factionId: 'redclaw',
    archetype: 'bandit',
    respawnGameHours: 'never',
    abilities: [
      {
        id: 'reaver_cleave',
        kind: 'frontal_cone',
        telegraphTicks: 40,
        interruptible: true,
        cooldownTicks: 240,
        damage: 26,
        channel: 'physical',
        coneDegrees: 110,
        range: 4.5,
      },
    ],
  },

  // --- the dungeon boss: multi-phase group encounter (D-018 exemplar) ------
  barrow_wight: {
    id: 'barrow_wight',
    name: 'The Pale Warden',
    kind: 'creature',
    level: 8,
    tier: 'boss',
    role: 'melee',
    baseStats: { maxHealth: 380, armor: 18, moveSpeed: 4.2, resistFrost: 0.6 },
    attack: 'melee',
    attackDamage: 20,
    attackChannel: 'frost',
    aggressive: true,
    fleeBelowHealthFrac: 0,
    perceptionRange: 26,
    factionId: 'pale_dead',
    lootTable: 'wight_loot',
    archetype: 'wight',
    respawnGameHours: 'never',
    interruptImmune: false,
    abilities: [
      {
        id: 'pale_breath',
        kind: 'frontal_cone',
        telegraphTicks: 45,
        interruptible: true,
        cooldownTicks: 300,
        damage: 42,
        channel: 'frost',
        coneDegrees: 90,
        range: 8,
      },
      {
        id: 'grave_chill',
        kind: 'ground_aoe',
        telegraphTicks: 30,
        interruptible: false,
        cooldownTicks: 360,
        channel: 'frost',
        aoeRadius: 3.5,
        aoeDps: 14,
        aoeTicks: 360,
      },
      {
        id: 'call_thralls',
        kind: 'summon',
        telegraphTicks: 60,
        interruptible: false,
        cooldownTicks: 900,
        summonActorId: 'barrow_thrall',
        summonCount: 2,
        maxActiveSummons: 4,
      },
    ],
    phases: [
      { healthFrac: 0.66, unlockAbilities: ['call_thralls'], damageMult: 1.15 },
      { healthFrac: 0.33, damageMult: 1.3 },
    ],
  },
  barrow_thrall: {
    id: 'barrow_thrall',
    name: 'Barrow Thrall',
    kind: 'creature',
    level: 5,
    tier: 'standard',
    role: 'melee',
    baseStats: { maxHealth: 50, moveSpeed: 4.8, resistFrost: 0.4 },
    attack: 'melee',
    attackDamage: 11,
    attackChannel: 'frost',
    aggressive: true,
    fleeBelowHealthFrac: 0,
    perceptionRange: 30,
    factionId: 'pale_dead',
    archetype: 'wight',
    respawnGameHours: 'never',
  },
  barrow_sentinel: {
    id: 'barrow_sentinel',
    name: 'Barrow Sentinel',
    kind: 'creature',
    level: 6,
    tier: 'veteran',
    role: 'melee',
    baseStats: { maxHealth: 130, armor: 16, moveSpeed: 4.4, resistFrost: 0.5 },
    attack: 'melee',
    attackDamage: 15,
    attackChannel: 'frost',
    aggressive: true,
    fleeBelowHealthFrac: 0,
    perceptionRange: 30,
    factionId: 'pale_dead',
    lootTable: 'sentinel_loot',
    archetype: 'wight',
    respawnGameHours: 'never',
    abilities: [
      {
        id: 'gravefrost_wake',
        kind: 'ground_aoe',
        telegraphTicks: 36,
        interruptible: true,
        cooldownTicks: 300,
        channel: 'frost',
        aoeRadius: 2.5,
        aoeDps: 8,
        aoeTicks: 180,
      },
    ],
  },

  // --- villagers -----------------------------------------------------------
  maera: {
    id: 'maera',
    name: 'Maera Fenn',
    kind: 'npc',
    level: 4,
    baseStats: { maxHealth: 80 },
    attack: 'melee',
    attackDamage: 5,
    attackChannel: 'physical',
    aggressive: false,
    fleeBelowHealthFrac: 0.5,
    perceptionRange: 20,
    factionId: 'fenharrow',
    dialogueId: 'maera_dialogue',
    merchant: { buys: ['weapon', 'armor', 'misc', 'ingredient', 'consumable', 'tome'], stockTable: 'merchant_stock', gold: 500 },
    schedule: [
      { fromHour: 7, toHour: 21, spaceId: 'fenharrow_inn', x: 4, z: 4, activity: 'work' },
      { fromHour: 21, toHour: 24, spaceId: 'fenharrow_inn', x: -5, z: 7, activity: 'sleep' },
      { fromHour: 0, toHour: 7, spaceId: 'fenharrow_inn', x: -5, z: 7, activity: 'sleep' },
    ],
    archetype: 'villager_f',
    respawnGameHours: 'never',
  },
  bronn: {
    id: 'bronn',
    name: 'Brandvar Hale',
    kind: 'npc',
    level: 5,
    baseStats: { maxHealth: 100 },
    attack: 'melee',
    attackDamage: 9,
    attackChannel: 'physical',
    aggressive: false,
    fleeBelowHealthFrac: 0.25,
    perceptionRange: 20,
    factionId: 'fenharrow',
    dialogueId: 'bronn_dialogue',
    schedule: [
      { fromHour: 6, toHour: 20, spaceId: 'kaldwyn', x: 67, z: 132, activity: 'work' },
      { fromHour: 20, toHour: 24, spaceId: 'fenharrow_inn', x: 3, z: 8, activity: 'idle' },
      { fromHour: 0, toHour: 6, spaceId: 'kaldwyn', x: 66, z: 132, activity: 'sleep' },
    ],
    archetype: 'villager_m',
    respawnGameHours: 'never',
  },
  ysolde: {
    id: 'ysolde',
    name: 'Eydris Varr',
    kind: 'npc',
    level: 3,
    baseStats: { maxHealth: 70 },
    attack: 'ranged',
    attackDamage: 7,
    attackChannel: 'physical',
    aggressive: false,
    fleeBelowHealthFrac: 0.3,
    perceptionRange: 30,
    factionId: 'fenharrow',
    dialogueId: 'ysolde_dialogue',
    schedule: [
      { fromHour: 5, toHour: 18, spaceId: 'kaldwyn', x: 10, z: 185, activity: 'wander' },
      { fromHour: 18, toHour: 23, spaceId: 'fenharrow_inn', x: 6, z: 6, activity: 'idle' },
      { fromHour: 23, toHour: 24, spaceId: 'kaldwyn', x: 27, z: 168, activity: 'sleep' },
      { fromHour: 0, toHour: 5, spaceId: 'kaldwyn', x: 27, z: 168, activity: 'sleep' },
    ],
    archetype: 'villager_f',
    respawnGameHours: 'never',
  },
  tamsin: {
    id: 'tamsin',
    name: 'Tamsin Reed',
    kind: 'npc',
    level: 3,
    baseStats: { maxHealth: 72 },
    attack: 'melee',
    attackDamage: 6,
    attackChannel: 'physical',
    aggressive: false,
    fleeBelowHealthFrac: 0.35,
    perceptionRange: 22,
    factionId: 'thornmere',
    dialogueId: 'tamsin_dialogue',
    schedule: [
      { fromHour: 6, toHour: 18, spaceId: 'kaldwyn', x: -22, z: -176, activity: 'work' },
      { fromHour: 18, toHour: 22, spaceId: 'kaldwyn', x: -8, z: -165, activity: 'idle' },
      { fromHour: 22, toHour: 24, spaceId: 'kaldwyn', x: -25, z: -190, activity: 'sleep' },
      { fromHour: 0, toHour: 6, spaceId: 'kaldwyn', x: -25, z: -190, activity: 'sleep' },
    ],
    archetype: 'villager_f',
    respawnGameHours: 'never',
  },
  corren: {
    id: 'corren',
    name: 'Corren Pike',
    kind: 'npc',
    level: 4,
    baseStats: { maxHealth: 84 },
    attack: 'ranged',
    attackDamage: 7,
    attackChannel: 'physical',
    aggressive: false,
    fleeBelowHealthFrac: 0.3,
    perceptionRange: 28,
    factionId: 'thornmere',
    dialogueId: 'corren_dialogue',
    schedule: [
      { fromHour: 5, toHour: 17, spaceId: 'kaldwyn', x: 8, z: -176, activity: 'wander' },
      { fromHour: 17, toHour: 22, spaceId: 'kaldwyn', x: -8, z: -165, activity: 'idle' },
      { fromHour: 22, toHour: 24, spaceId: 'kaldwyn', x: 7, z: -197, activity: 'sleep' },
      { fromHour: 0, toHour: 5, spaceId: 'kaldwyn', x: 7, z: -197, activity: 'sleep' },
    ],
    archetype: 'villager_m',
    respawnGameHours: 'never',
  },
  vael: {
    id: 'vael',
    name: 'Vael Orin',
    kind: 'npc',
    level: 2,
    baseStats: { maxHealth: 68 },
    attack: 'melee',
    attackDamage: 5,
    attackChannel: 'physical',
    aggressive: false,
    fleeBelowHealthFrac: 0.4,
    perceptionRange: 20,
    factionId: 'thornmere',
    dialogueId: 'vael_dialogue',
    schedule: [
      { fromHour: 6, toHour: 19, spaceId: 'kaldwyn', x: -5, z: -205, activity: 'work' },
      { fromHour: 19, toHour: 23, spaceId: 'kaldwyn', x: -18, z: -175, activity: 'idle' },
      { fromHour: 23, toHour: 24, spaceId: 'kaldwyn', x: 8, z: -163, activity: 'sleep' },
      { fromHour: 0, toHour: 6, spaceId: 'kaldwyn', x: 8, z: -163, activity: 'sleep' },
    ],
    archetype: 'villager_m',
    respawnGameHours: 'never',
  },
};
