// Item catalog. Exemplars for every item kind; Opus expands via OPUS_BACKLOG
// tickets following these templates. All records validated by schema.ts.

import type { ItemDef } from './schema';

export const ITEMS: Record<string, ItemDef> = {
  // --- weapons (exemplars: sword, dagger, bow) -----------------------------
  iron_sword: {
    id: 'iron_sword',
    name: 'Iron Sword',
    kind: 'weapon',
    weaponType: 'sword',
    damage: 8,
    damageChannel: 'physical',
    skill: 'oneHanded',
    weight: 9,
    value: 25,
  },
  iron_axe: {
    id: 'iron_axe',
    name: 'Iron Axe',
    kind: 'weapon',
    weaponType: 'axe',
    damage: 9,
    damageChannel: 'physical',
    skill: 'oneHanded',
    weight: 11,
    value: 28,
  },
  iron_dagger: {
    id: 'iron_dagger',
    name: 'Iron Dagger',
    kind: 'weapon',
    weaponType: 'dagger',
    damage: 6,
    damageChannel: 'physical',
    skill: 'oneHanded',
    weight: 3,
    value: 20,
  },
  iron_mace: {
    id: 'iron_mace',
    name: 'Iron Mace',
    kind: 'weapon',
    // The existing axe timing is the established heavy one-hand profile.
    weaponType: 'axe',
    damage: 9,
    damageChannel: 'physical',
    skill: 'oneHanded',
    weight: 12,
    value: 30,
  },
  ironbound_bow: {
    id: 'ironbound_bow',
    name: 'Ironbound Bow',
    kind: 'weapon',
    weaponType: 'bow',
    damage: 8,
    damageChannel: 'physical',
    skill: 'archery',
    weight: 6,
    value: 38,
  },
  worn_dagger: {
    id: 'worn_dagger',
    name: 'Worn Dagger',
    kind: 'weapon',
    weaponType: 'dagger',
    damage: 4,
    damageChannel: 'physical',
    skill: 'oneHanded',
    weight: 2,
    value: 8,
  },
  hunting_bow: {
    id: 'hunting_bow',
    name: 'Hunting Bow',
    kind: 'weapon',
    weaponType: 'bow',
    damage: 7,
    damageChannel: 'physical',
    skill: 'archery',
    weight: 5,
    value: 30,
  },
  steel_sword: {
    id: 'steel_sword',
    name: 'Steel Sword',
    kind: 'weapon',
    weaponType: 'sword',
    damage: 11,
    damageChannel: 'physical',
    skill: 'oneHanded',
    weight: 10,
    value: 60,
  },

  // --- ammo / misc ---------------------------------------------------------
  arrow: {
    id: 'arrow',
    name: 'Arrow',
    kind: 'misc',
    stackable: true,
    weight: 0,
    value: 1,
  },

  // --- armor (exemplars: body, head, feet, shield-as-offHand) --------------
  leather_cuirass: {
    id: 'leather_cuirass',
    name: 'Leather Cuirass',
    kind: 'armor',
    slot: 'body',
    armor: 12,
    skill: 'lightArmor',
    weight: 6,
    value: 35,
  },
  leather_helmet: {
    id: 'leather_helmet',
    name: 'Leather Helmet',
    kind: 'armor',
    slot: 'head',
    armor: 5,
    skill: 'lightArmor',
    weight: 2,
    value: 15,
  },
  leather_boots: {
    id: 'leather_boots',
    name: 'Leather Boots',
    kind: 'armor',
    slot: 'feet',
    armor: 4,
    skill: 'lightArmor',
    weight: 2,
    value: 12,
  },
  wooden_shield: {
    id: 'wooden_shield',
    name: 'Wooden Shield',
    kind: 'armor',
    slot: 'offHand',
    armor: 6,
    skill: 'block',
    equipMods: [{ stat: 'blockMitigation', op: 'add', value: 0.15, source: 'item:wooden_shield' }],
    weight: 5,
    value: 20,
  },
  hide_cuirass: {
    id: 'hide_cuirass',
    name: 'Stitched Hide Cuirass',
    kind: 'armor',
    slot: 'body',
    armor: 9,
    skill: 'lightArmor',
    weight: 5,
    value: 24,
  },
  hide_cap: {
    id: 'hide_cap',
    name: 'Stitched Hide Cap',
    kind: 'armor',
    slot: 'head',
    armor: 3,
    skill: 'lightArmor',
    weight: 1.5,
    value: 10,
  },
  hide_boots: {
    id: 'hide_boots',
    name: 'Stitched Hide Boots',
    kind: 'armor',
    slot: 'feet',
    armor: 3,
    skill: 'lightArmor',
    weight: 1.5,
    value: 9,
  },
  hide_shield: {
    id: 'hide_shield',
    name: 'Hidebound Shield',
    kind: 'armor',
    slot: 'offHand',
    armor: 4,
    skill: 'block',
    equipMods: [{ stat: 'blockMitigation', op: 'add', value: 0.1, source: 'item:hide_shield' }],
    weight: 4,
    value: 16,
  },
  fur_cuirass: {
    id: 'fur_cuirass',
    name: 'Rime Fur Cuirass',
    kind: 'armor',
    slot: 'body',
    armor: 10,
    skill: 'lightArmor',
    weight: 7,
    value: 28,
  },
  fur_hood: {
    id: 'fur_hood',
    name: 'Rime Fur Hood',
    kind: 'armor',
    slot: 'head',
    armor: 4,
    skill: 'lightArmor',
    weight: 2,
    value: 12,
  },
  fur_boots: {
    id: 'fur_boots',
    name: 'Rime Fur Boots',
    kind: 'armor',
    slot: 'feet',
    armor: 3,
    skill: 'lightArmor',
    weight: 2,
    value: 10,
  },
  fur_mantle: {
    id: 'fur_mantle',
    name: 'Rime Fur Mantle',
    kind: 'armor',
    slot: 'amulet',
    armor: 2,
    skill: 'lightArmor',
    weight: 2,
    value: 15,
  },

  // --- consumables ---------------------------------------------------------
  healing_draught: {
    id: 'healing_draught',
    name: 'Healing Draught',
    kind: 'consumable',
    useEffects: ['restore_health'],
    stackable: true,
    weight: 0.5,
    value: 18,
  },
  stamina_tonic: {
    id: 'stamina_tonic',
    name: 'Stamina Tonic',
    kind: 'consumable',
    useEffects: ['restore_stamina'],
    stackable: true,
    weight: 0.5,
    value: 14,
  },

  // --- spell primers ------------------------------------------------------
  primer_flamebolt: {
    id: 'primer_flamebolt', name: 'Ember Script: Flamebolt', kind: 'tome',
    teachesSpell: 'flamebolt', weight: 1, value: 55,
  },
  primer_frostspike: {
    id: 'primer_frostspike', name: 'Rime Script: Frostspike', kind: 'tome',
    teachesSpell: 'frostspike', weight: 1, value: 65,
  },
  primer_stormneedle: {
    id: 'primer_stormneedle', name: 'Storm Script: Stormneedle', kind: 'tome',
    teachesSpell: 'stormneedle', weight: 1, value: 75,
  },
  primer_mend_wounds: {
    id: 'primer_mend_wounds', name: "Mender's Primer: Mend Wounds", kind: 'tome',
    teachesSpell: 'mend_wounds', weight: 1, value: 60,
  },
  primer_stoneward: {
    id: 'primer_stoneward', name: "Stonebinder's Primer: Stoneward", kind: 'tome',
    teachesSpell: 'stoneward', weight: 1, value: 80,
  },
  primer_veilstep: {
    id: 'primer_veilstep', name: "Veilwright's Primer: Veilstep", kind: 'tome',
    teachesSpell: 'veilstep', weight: 1, value: 85,
  },

  // --- ingredients (alchemy exemplars) -------------------------------------
  frost_moss: {
    id: 'frost_moss',
    name: 'Frost Moss',
    kind: 'ingredient',
    stackable: true,
    weight: 0.1,
    value: 3,
  },
  ember_cap: {
    id: 'ember_cap',
    name: 'Ember Cap',
    kind: 'ingredient',
    stackable: true,
    weight: 0.1,
    value: 4,
  },

  // --- quest items ---------------------------------------------------------
  prospectors_journal: {
    id: 'prospectors_journal',
    name: "Hadrin's Journal",
    kind: 'quest',
    weight: 0.2,
    value: 0,
  },
  duskhollow_ore: {
    id: 'duskhollow_ore',
    name: 'Pale Ore Sample',
    kind: 'quest',
    stackable: true,
    weight: 1,
    value: 0,
  },

  // --- misc / economy ------------------------------------------------------
  wolf_pelt: {
    id: 'wolf_pelt',
    name: 'Wolf Pelt',
    kind: 'misc',
    stackable: true,
    weight: 1.5,
    value: 10,
  },
  bread: {
    id: 'bread',
    name: 'Hearth Bread',
    kind: 'consumable',
    useEffects: ['restore_health_small'],
    stackable: true,
    weight: 0.3,
    value: 3,
  },
};
