// Effects, spells, and perks. One exemplar per mechanical shape:
// instant restore, DoT, stat buff/debuff, projectile spell, self heal spell,
// flat perk, prerequisite perk.

import type { EffectDef, PerkDef, SpellDef } from './schema';

export const EFFECTS: Record<string, EffectDef> = {
  restore_health: {
    id: 'restore_health',
    name: 'Restore Health',
    duration: 3,
    stackRule: 'refresh',
    maxStacks: 1,
    mods: [],
    hot: { perSecond: 12 },
  },
  restore_health_small: {
    id: 'restore_health_small',
    name: 'Nourished',
    duration: 4,
    stackRule: 'refresh',
    maxStacks: 1,
    mods: [],
    hot: { perSecond: 2 },
  },
  restore_stamina: {
    id: 'restore_stamina',
    name: 'Restore Stamina',
    duration: 3,
    stackRule: 'refresh',
    maxStacks: 1,
    mods: [{ stat: 'staminaRegen', op: 'add', value: 15, source: 'effect:restore_stamina' }],
  },
  burning: {
    id: 'burning',
    name: 'Burning',
    duration: 4,
    stackRule: 'refresh',
    maxStacks: 1,
    mods: [],
    dot: { channel: 'fire', perSecond: 3 },
  },
  chilled: {
    id: 'chilled',
    name: 'Chilled',
    duration: 5,
    stackRule: 'refresh',
    maxStacks: 1,
    mods: [{ stat: 'moveSpeed', op: 'mul', value: 0.7, source: 'effect:chilled' }],
  },
  regeneration: {
    id: 'regeneration',
    name: 'Regeneration',
    duration: 10,
    stackRule: 'refresh',
    maxStacks: 1,
    mods: [],
    hot: { perSecond: 4 },
  },
};

export const SPELLS: Record<string, SpellDef> = {
  flamebolt: {
    id: 'flamebolt',
    name: 'Flamebolt',
    kind: 'projectile',
    magickaCost: 14,
    damage: 10,
    channel: 'fire',
    applyEffects: ['burning'],
    skill: 'destruction',
  },
  frostspike: {
    id: 'frostspike',
    name: 'Frostspike',
    kind: 'projectile',
    magickaCost: 16,
    damage: 8,
    channel: 'frost',
    applyEffects: ['chilled'],
    skill: 'destruction',
  },
  mend_wounds: {
    id: 'mend_wounds',
    name: 'Mend Wounds',
    kind: 'self',
    magickaCost: 12,
    heal: 18,
    applyEffects: ['regeneration'],
    skill: 'restoration',
  },
};

export const PERKS: Record<string, PerkDef> = {
  bladesman: {
    id: 'bladesman',
    name: 'Bladesman',
    description: 'One-handed weapons deal 20% more damage.',
    skill: 'oneHanded',
    requiredSkillLevel: 2,
    mods: [{ stat: 'meleeDamage', op: 'mul', value: 1.2, source: 'perk:bladesman' }],
  },
  bladesman_2: {
    id: 'bladesman_2',
    name: 'Bladesman II',
    description: 'One-handed weapons deal a further 20% more damage.',
    skill: 'oneHanded',
    requiredSkillLevel: 5,
    requiresPerk: 'bladesman',
    mods: [{ stat: 'meleeDamage', op: 'mul', value: 1.2, source: 'perk:bladesman_2' }],
  },
  eagle_eye: {
    id: 'eagle_eye',
    name: 'Eagle Eye',
    description: 'Bows deal 20% more damage.',
    skill: 'archery',
    requiredSkillLevel: 2,
    mods: [{ stat: 'rangedDamage', op: 'mul', value: 1.2, source: 'perk:eagle_eye' }],
  },
  eagle_eye_2: {
    id: 'eagle_eye_2',
    name: 'Eagle Eye II',
    description: 'Bows deal a further 15% more damage.',
    skill: 'archery',
    requiredSkillLevel: 5,
    requiresPerk: 'eagle_eye',
    mods: [{ stat: 'rangedDamage', op: 'mul', value: 1.15, source: 'perk:eagle_eye_2' }],
  },
  eagle_eye_3: {
    id: 'eagle_eye_3',
    name: 'Eagle Eye III',
    description: 'Bows deal a final 15% more damage.',
    skill: 'archery',
    requiredSkillLevel: 9,
    requiresPerk: 'eagle_eye_2',
    mods: [{ stat: 'rangedDamage', op: 'mul', value: 1.15, source: 'perk:eagle_eye_3' }],
  },
  shadowfoot: {
    id: 'shadowfoot',
    name: 'Shadowfoot',
    description: 'You are 30% harder to detect while sneaking.',
    skill: 'sneak',
    requiredSkillLevel: 2,
    mods: [{ stat: 'stealth', op: 'mul', value: 1.3, source: 'perk:shadowfoot' }],
  },
  shadowfoot_2: {
    id: 'shadowfoot_2',
    name: 'Shadowfoot II',
    description: 'You are a further 20% harder to detect while sneaking.',
    skill: 'sneak',
    requiredSkillLevel: 5,
    requiresPerk: 'shadowfoot',
    mods: [{ stat: 'stealth', op: 'mul', value: 1.2, source: 'perk:shadowfoot_2' }],
  },
  shadowfoot_3: {
    id: 'shadowfoot_3',
    name: 'Shadowfoot III',
    description: 'You are a final 20% harder to detect while sneaking.',
    skill: 'sneak',
    requiredSkillLevel: 9,
    requiresPerk: 'shadowfoot_2',
    mods: [{ stat: 'stealth', op: 'mul', value: 1.2, source: 'perk:shadowfoot_3' }],
  },
  stalwart: {
    id: 'stalwart',
    name: 'Stalwart',
    description: 'Blocking mitigates an additional 10% of damage.',
    skill: 'block',
    requiredSkillLevel: 2,
    mods: [{ stat: 'blockMitigation', op: 'add', value: 0.1, source: 'perk:stalwart' }],
  },
  stalwart_2: {
    id: 'stalwart_2',
    name: 'Stalwart II',
    description: 'Blocking mitigates an additional 8% of damage.',
    skill: 'block',
    requiredSkillLevel: 5,
    requiresPerk: 'stalwart',
    mods: [{ stat: 'blockMitigation', op: 'add', value: 0.08, source: 'perk:stalwart_2' }],
  },
  stalwart_3: {
    id: 'stalwart_3',
    name: 'Stalwart III',
    description: 'Blocking mitigates an additional 7% of damage.',
    skill: 'block',
    requiredSkillLevel: 9,
    requiresPerk: 'stalwart_2',
    mods: [{ stat: 'blockMitigation', op: 'add', value: 0.07, source: 'perk:stalwart_3' }],
  },
  wayfarers_grace: {
    id: 'wayfarers_grace',
    name: "Wayfarer's Grace",
    description: 'Light-armor training increases movement speed by 4%.',
    skill: 'lightArmor',
    requiredSkillLevel: 2,
    mods: [{ stat: 'moveSpeed', op: 'mul', value: 1.04, source: 'perk:wayfarers_grace' }],
  },
  wayfarers_grace_2: {
    id: 'wayfarers_grace_2',
    name: "Wayfarer's Grace II",
    description: 'Light-armor training grants a further 4% movement speed.',
    skill: 'lightArmor',
    requiredSkillLevel: 6,
    requiresPerk: 'wayfarers_grace',
    mods: [{ stat: 'moveSpeed', op: 'mul', value: 1.04, source: 'perk:wayfarers_grace_2' }],
  },
  wellspring: {
    id: 'wellspring',
    name: 'Wellspring',
    description: 'Restoration training increases magicka regeneration.',
    skill: 'restoration',
    requiredSkillLevel: 2,
    mods: [{ stat: 'magickaRegen', op: 'add', value: 0.75, source: 'perk:wellspring' }],
  },
  wellspring_2: {
    id: 'wellspring_2',
    name: 'Wellspring II',
    description: 'Restoration training further increases magicka regeneration.',
    skill: 'restoration',
    requiredSkillLevel: 6,
    requiresPerk: 'wellspring',
    mods: [{ stat: 'magickaRegen', op: 'add', value: 0.75, source: 'perk:wellspring_2' }],
  },
};
